[build]
  publish = "."
  command = "./build.sh"

[build.environment]
  # Tell Netlify these are intentionally public environment variables
  NODE_VERSION = "18"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
