[build]
  publish = "."

[build.environment]
  # Tell Netlify these are intentionally public environment variables
  NODE_VERSION = "18"
  # Disable secrets scanning for public values
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_URL,NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
