#!/bin/bash

# FlowState App - Screenshot Generation Helper
echo "📸 FlowState App - App Store Screenshot Helper"
echo "============================================="

PROJECT_PATH="/Users/broneotodak/Projects/flowstate-ai/ios-app/FlowStateApp"
SCREENSHOTS_DIR="$PROJECT_PATH/app-store-assets/screenshots"

# Create screenshots directory
echo "📁 Creating screenshots directory..."
mkdir -p "$SCREENSHOTS_DIR/iPhone"
mkdir -p "$SCREENSHOTS_DIR/iPad" 
mkdir -p "$SCREENSHOTS_DIR/macOS"

echo "✅ Created screenshot directories:"
echo "  - $SCREENSHOTS_DIR/iPhone"
echo "  - $SCREENSHOTS_DIR/iPad"
echo "  - $SCREENSHOTS_DIR/macOS"

echo ""
echo "📱 REQUIRED SCREENSHOT SPECIFICATIONS:"
echo "======================================"
echo ""
echo "📱 iPhone 15 Pro Max (6.7\" Display):"
echo "  - Resolution: 1290 x 2796 pixels"
echo "  - Format: PNG or JPEG"
echo "  - Quantity: 1-10 screenshots"
echo "  - Save to: $SCREENSHOTS_DIR/iPhone/"

echo ""
echo "📱 iPad Pro 12.9\" Display:"
echo "  - Resolution: 2048 x 2732 pixels (Portrait)"
echo "  - Format: PNG or JPEG"  
echo "  - Quantity: 1-10 screenshots"
echo "  - Save to: $SCREENSHOTS_DIR/iPad/"

echo ""
echo "💻 macOS Screenshots:"
echo "  - Minimum: 1280 x 800 pixels"
echo "  - Recommended: 1920 x 1080 pixels"
echo "  - Format: PNG or JPEG"
echo "  - Quantity: 1-10 screenshots"
echo "  - Save to: $SCREENSHOTS_DIR/macOS/"

echo ""
echo "🎯 SUGGESTED SCREENSHOT SEQUENCE:"
echo "================================="
echo "1. 📊 Multi-Project Dashboard (main screen)"
echo "2. 🔗 GitHub Integration Settings"
echo "3. 📈 Activity Tracking & Flow States"
echo "4. 📁 Individual Project View"
echo "5. ⚙️  App Settings & Configuration"

echo ""
echo "📱 HOW TO TAKE SCREENSHOTS:"
echo "==========================="
echo ""
echo "🔧 For iPhone/iPad (via Xcode Simulator):"
echo "1. Open FlowStateApp.xcodeproj in Xcode"
echo "2. Select iPhone 15 Pro Max simulator"
echo "3. Build and run the app (Cmd+R)"
echo "4. Navigate to each screen you want to capture"
echo "5. Use Device > Screenshot (or Cmd+S in simulator)"
echo "6. Simulator saves screenshots to ~/Desktop"
echo "7. Move screenshots to appropriate folders"

echo ""
echo "💻 For macOS Screenshots:"
echo "1. Build and run for macOS target"
echo "2. Use Cmd+Shift+4 to capture specific windows"
echo "3. Or use Cmd+Shift+5 for advanced screenshot options"
echo "4. Save to $SCREENSHOTS_DIR/macOS/"

echo ""
echo "🖼️  SCREENSHOT CONTENT SUGGESTIONS:"
echo "=================================="
echo ""
echo "Screenshot 1 - Dashboard:"
echo "• Show multiple active projects"
echo "• Display GitHub integration status"
echo "• Include productivity metrics"
echo "• Highlight key features"

echo ""
echo "Screenshot 2 - GitHub Integration:"
echo "• Show GitHub settings screen"
echo "• Display connected repositories"
echo "• Show API token setup (hide actual token)"
echo "• Highlight security features"

echo ""
echo "Screenshot 3 - Activity Tracking:"
echo "• Show real-time activity monitoring"
echo "• Display flow state visualization"
echo "• Include time tracking elements"
echo "• Show productivity insights"

echo ""
echo "Screenshot 4 - Project Details:"
echo "• Individual project view"
echo "• Commit history display"
echo "• Project statistics"
echo "• GitHub repository information"

echo ""
echo "Screenshot 5 - Settings:"
echo "• App configuration options"
echo "• Privacy settings"
echo "• Notification preferences"
echo "• Theme/appearance options"

echo ""
echo "✅ AFTER TAKING SCREENSHOTS:"
echo "============================"
echo "1. Verify image dimensions match requirements"
echo "2. Check file sizes (should be under 8MB each)"
echo "3. Ensure no sensitive information is visible"
echo "4. Test that images look good at App Store preview sizes"
echo "5. Upload to App Store Connect"

echo ""
echo "🚀 NEXT STEPS:"
echo "=============="
echo "1. Take all required screenshots"
echo "2. Go to https://appstoreconnect.apple.com"
echo "3. Navigate to FlowState AI app"
echo "4. Upload screenshots to appropriate sections"
echo "5. Complete app metadata"
echo "6. Submit Build #7 for review"

echo ""
echo "📁 Screenshot directories ready at:"
echo "$SCREENSHOTS_DIR"
